-- Migration 000001: Initial Schema  
-- This migration creates the complete working schema from sql/schema.sql

-- Disable foreign key checks for clean setup
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `api_configurations` (
  `id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `variation_name` varchar(255) NOT NULL,
  `model_name` varchar(255) NOT NULL,
  `system_prompt` text,
  `temperature` decimal(3,2) DEFAULT NULL,
  `max_tokens` int DEFAULT NULL,
  `top_p` decimal(3,2) DEFAULT NULL,
  `top_k` int DEFAULT NULL,
  `safety_settings` json,
  `generation_config` json,
  `tools` json,
  `tool_config` json,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_config` (`user_id`,`variation_name`),
  KEY `idx_api_configurations_user_id` (`user_id`),
  CONSTRAINT `api_configurations_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `api_requests` (
  `id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `execution_run_id` varchar(255) NOT NULL,
  `configuration_id` varchar(255) NOT NULL,
  `request_type` varchar(100) DEFAULT NULL,
  `prompt` text,
  `context` text,
  `function_name` varchar(100) DEFAULT NULL,
  `function_parameters` json,
  `request_headers` json,
  `request_body` json NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_api_requests_execution_run_id` (`execution_run_id`),
  KEY `idx_api_requests_configuration_id` (`configuration_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `api_requests_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `api_requests_ibfk_2` FOREIGN KEY (`execution_run_id`) REFERENCES `execution_runs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `api_requests_ibfk_3` FOREIGN KEY (`configuration_id`) REFERENCES `api_configurations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `api_responses` (
  `id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `request_id` varchar(255) NOT NULL,
  `response_status` varchar(50) DEFAULT NULL,
  `response_text` text,
  `function_call_response` json,
  `usage_metadata` json,
  `safety_ratings` json,
  `finish_reason` varchar(50) DEFAULT NULL,
  `error_message` text,
  `response_time_ms` int DEFAULT NULL,
  `response_headers` json,
  `response_body` json,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_api_responses_request_id` (`request_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `api_responses_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `api_responses_ibfk_2` FOREIGN KEY (`request_id`) REFERENCES `api_requests` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `comparison_results` (
  `id` varchar(255) NOT NULL,
  `execution_run_id` varchar(255) NOT NULL,
  `comparison_type` varchar(100) DEFAULT NULL,
  `metric_name` varchar(100) DEFAULT NULL,
  `configuration_scores` json,
  `best_configuration_id` varchar(255) DEFAULT NULL,
  `best_configuration_data` json,
  `all_configurations_data` json,
  `analysis_notes` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `execution_run_id` (`execution_run_id`),
  KEY `best_configuration_id` (`best_configuration_id`),
  CONSTRAINT `comparison_results_ibfk_1` FOREIGN KEY (`execution_run_id`) REFERENCES `execution_runs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `comparison_results_ibfk_2` FOREIGN KEY (`best_configuration_id`) REFERENCES `api_configurations` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_configurations` (
  `id` varchar(255) NOT NULL,
  `execution_run_id` varchar(255) NOT NULL,
  `configuration_id` varchar(255) NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_execution_config` (`execution_run_id`,`configuration_id`),
  KEY `configuration_id` (`configuration_id`),
  CONSTRAINT `execution_configurations_ibfk_1` FOREIGN KEY (`execution_run_id`) REFERENCES `execution_runs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_configurations_ibfk_2` FOREIGN KEY (`configuration_id`) REFERENCES `api_configurations` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_flow_events` (
  `id` varchar(255) NOT NULL,
  `execution_run_id` varchar(255) NOT NULL,
  `request_id` varchar(255) DEFAULT NULL,
  `event_type` enum('prompt_start','ai_model_call','function_call_start','function_call_end','ai_response','error_occurred','retry_attempt','execution_complete') NOT NULL,
  `sequence_number` int NOT NULL DEFAULT '0',
  `parent_event_id` varchar(255) DEFAULT NULL,
  `event_data` json,
  `duration_ms` int DEFAULT NULL,
  `status` enum('pending','success','error','timeout') DEFAULT 'pending',
  `error_message` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_execution_flow_events_request` (`request_id`),
  KEY `idx_execution_flow_events_execution_run` (`execution_run_id`),
  KEY `idx_execution_flow_events_sequence` (`execution_run_id`,`sequence_number`),
  KEY `idx_execution_flow_events_type` (`event_type`),
  KEY `idx_execution_flow_events_parent` (`parent_event_id`),
  CONSTRAINT `fk_execution_flow_events_execution_run` FOREIGN KEY (`execution_run_id`) REFERENCES `execution_runs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_execution_flow_events_parent` FOREIGN KEY (`parent_event_id`) REFERENCES `execution_flow_events` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_execution_flow_events_request` FOREIGN KEY (`request_id`) REFERENCES `api_requests` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_function_configs` (
  `id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `execution_run_id` varchar(255) NOT NULL,
  `function_definition_id` varchar(255) NOT NULL,
  `use_mock_response` tinyint(1) DEFAULT '0',
  `execution_order` int DEFAULT '0',
  `config` json,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `function_definition_id` (`function_definition_id`),
  KEY `idx_execution_function_configs_user_id` (`user_id`),
  KEY `idx_execution_function_configs_execution_run_id` (`execution_run_id`),
  CONSTRAINT `execution_function_configs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_function_configs_ibfk_2` FOREIGN KEY (`execution_run_id`) REFERENCES `execution_runs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_function_configs_ibfk_3` FOREIGN KEY (`function_definition_id`) REFERENCES `function_definitions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_logs` (
  `id` varchar(255) NOT NULL,
  `execution_run_id` varchar(255) NOT NULL,
  `configuration_id` varchar(255) DEFAULT NULL,
  `request_id` varchar(255) DEFAULT NULL,
  `log_level` varchar(20) DEFAULT 'INFO',
  `log_category` varchar(50) DEFAULT NULL,
  `message` text NOT NULL,
  `details` json,
  `timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `sequence_number` int DEFAULT NULL,
  `duration_ms` int DEFAULT NULL,
  `related_event_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `request_id` (`request_id`),
  KEY `idx_execution_logs_execution_run_id` (`execution_run_id`),
  KEY `idx_execution_logs_configuration_id` (`configuration_id`),
  KEY `idx_execution_logs_sequence` (`execution_run_id`,`sequence_number`),
  KEY `idx_execution_logs_event` (`related_event_id`),
  CONSTRAINT `execution_logs_ibfk_1` FOREIGN KEY (`execution_run_id`) REFERENCES `execution_runs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_logs_ibfk_2` FOREIGN KEY (`configuration_id`) REFERENCES `api_configurations` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_logs_ibfk_3` FOREIGN KEY (`request_id`) REFERENCES `api_requests` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_execution_logs_flow_event` FOREIGN KEY (`related_event_id`) REFERENCES `execution_flow_events` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_runs` (
  `id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `base_prompt` text,
  `context_prompt` text,
  `enable_function_calling` tinyint(1) NOT NULL DEFAULT '0',
  `status` enum('pending','running','completed','failed') DEFAULT 'pending',
  `error_message` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `agent_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_execution_runs_user_id` (`user_id`),
  KEY `idx_execution_runs_created_at` (`created_at`),
  KEY `idx_execution_runs_agent_id` (`agent_id`),
  CONSTRAINT `execution_runs_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_execution_runs_agent_id` FOREIGN KEY (`agent_id`) REFERENCES `agents` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_stats` (
  `id` varchar(255) NOT NULL,
  `execution_run_id` varchar(255) NOT NULL,
  `total_function_calls` int DEFAULT '0',
  `total_ai_model_calls` int DEFAULT '0',
  `total_errors` int DEFAULT '0',
  `total_retries` int DEFAULT '0',
  `total_execution_time_ms` int DEFAULT '0',
  `avg_function_call_time_ms` decimal(10,2) DEFAULT '0.00',
  `avg_ai_response_time_ms` decimal(10,2) DEFAULT '0.00',
  `max_execution_depth` int DEFAULT '0',
  `function_call_breakdown` json,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_execution_stats_execution_run` (`execution_run_id`),
  CONSTRAINT `fk_execution_stats_execution_run` FOREIGN KEY (`execution_run_id`) REFERENCES `execution_runs` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_template_auth_tokens` (
  `id` varchar(255) NOT NULL,
  `template_id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `token_value` varchar(255) NOT NULL,
  `token_name` varchar(100) NOT NULL,
  `description` text,
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `expires_at` timestamp NULL DEFAULT NULL,
  `custom_rate_limit_per_hour` int DEFAULT NULL,
  `custom_rate_limit_per_day` int DEFAULT NULL,
  `custom_rate_limit_burst` int DEFAULT NULL,
  `total_uses` int DEFAULT '0',
  `last_used_at` timestamp NULL DEFAULT NULL,
  `last_used_ip` varchar(45) DEFAULT NULL,
  `allowed_origins` json,
  `allowed_ips` json,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token_value` (`token_value`),
  KEY `idx_execution_template_auth_tokens_template_id` (`template_id`),
  KEY `idx_execution_template_auth_tokens_user_id` (`user_id`),
  KEY `idx_execution_template_auth_tokens_token_value` (`token_value`),
  KEY `idx_execution_template_auth_tokens_is_active` (`is_active`),
  KEY `idx_execution_template_auth_tokens_expires_at` (`expires_at`),
  CONSTRAINT `execution_template_auth_tokens_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `execution_templates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_template_auth_tokens_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_template_executions` (
  `id` varchar(255) NOT NULL,
  `template_id` varchar(255) NOT NULL,
  `template_version_id` varchar(255) DEFAULT NULL,
  `auth_token_id` varchar(255) DEFAULT NULL,
  `execution_run_id` varchar(255) DEFAULT NULL,
  `parameters_provided` json NOT NULL,
  `resolved_prompt` text NOT NULL,
  `resolved_context` text,
  `request_ip` varchar(45) DEFAULT NULL,
  `user_agent` text,
  `referer` varchar(500) DEFAULT NULL,
  `status` enum('pending','running','completed','failed','rate_limited') NOT NULL DEFAULT 'pending',
  `error_message` text,
  `execution_time_ms` int DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `template_version_id` (`template_version_id`),
  KEY `idx_execution_template_executions_template_id` (`template_id`),
  KEY `idx_execution_template_executions_auth_token_id` (`auth_token_id`),
  KEY `idx_execution_template_executions_status` (`status`),
  KEY `idx_execution_template_executions_created_at` (`created_at`),
  KEY `idx_execution_template_executions_execution_run_id` (`execution_run_id`),
  CONSTRAINT `execution_template_executions_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `execution_templates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_template_executions_ibfk_2` FOREIGN KEY (`template_version_id`) REFERENCES `execution_template_versions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `execution_template_executions_ibfk_3` FOREIGN KEY (`auth_token_id`) REFERENCES `execution_template_auth_tokens` (`id`) ON DELETE SET NULL,
  CONSTRAINT `execution_template_executions_ibfk_4` FOREIGN KEY (`execution_run_id`) REFERENCES `execution_runs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_template_functions` (
  `id` varchar(255) NOT NULL,
  `template_id` varchar(255) NOT NULL,
  `function_id` varchar(255) NOT NULL,
  `is_required` tinyint(1) NOT NULL DEFAULT '0',
  `execution_order` int DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_template_function` (`template_id`,`function_id`),
  KEY `idx_execution_template_functions_template_id` (`template_id`),
  KEY `idx_execution_template_functions_function_id` (`function_id`),
  KEY `idx_execution_template_functions_execution_order` (`template_id`,`execution_order`),
  CONSTRAINT `execution_template_functions_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `execution_templates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_template_functions_ibfk_2` FOREIGN KEY (`function_id`) REFERENCES `function_definitions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_template_parameter_versions` (
  `id` varchar(255) NOT NULL,
  `template_version_id` varchar(255) NOT NULL,
  `parameter_name` varchar(100) NOT NULL,
  `parameter_type` enum('string','number','boolean','array','object') NOT NULL,
  `description` text,
  `default_value` text,
  `is_required` tinyint(1) NOT NULL,
  `validation_rules` json,
  `allowed_values` json,
  `allow_sql_keywords` tinyint(1) NOT NULL DEFAULT '0',
  `allow_special_chars` tinyint(1) NOT NULL DEFAULT '1',
  `sanitize_html` tinyint(1) NOT NULL DEFAULT '1',
  `display_order` int DEFAULT '0',
  `ui_component` enum('text','textarea','select','multiselect','checkbox','number','date') DEFAULT 'text',
  `placeholder_text` varchar(255) DEFAULT NULL,
  `help_text` text,
  PRIMARY KEY (`id`),
  KEY `idx_execution_template_parameter_versions_template_version_id` (`template_version_id`),
  KEY `idx_execution_template_parameter_versions_display_order` (`template_version_id`,`display_order`),
  CONSTRAINT `execution_template_parameter_versions_ibfk_1` FOREIGN KEY (`template_version_id`) REFERENCES `execution_template_versions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_template_parameters` (
  `id` varchar(255) NOT NULL,
  `template_id` varchar(255) NOT NULL,
  `parameter_name` varchar(100) NOT NULL,
  `parameter_type` enum('string','number','boolean','array','object') NOT NULL DEFAULT 'string',
  `description` text,
  `default_value` text,
  `is_required` tinyint(1) NOT NULL DEFAULT '0',
  `validation_rules` json,
  `allowed_values` json,
  `allow_sql_keywords` tinyint(1) NOT NULL DEFAULT '0',
  `allow_special_chars` tinyint(1) NOT NULL DEFAULT '1',
  `sanitize_html` tinyint(1) NOT NULL DEFAULT '1',
  `display_order` int DEFAULT '0',
  `ui_component` enum('text','textarea','select','multiselect','checkbox','number','date') DEFAULT 'text',
  `placeholder_text` varchar(255) DEFAULT NULL,
  `help_text` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_template_parameter_name` (`template_id`,`parameter_name`),
  KEY `idx_execution_template_parameters_template_id` (`template_id`),
  KEY `idx_execution_template_parameters_display_order` (`template_id`,`display_order`),
  CONSTRAINT `execution_template_parameters_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `execution_templates` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_template_rate_limits` (
  `id` varchar(255) NOT NULL,
  `template_id` varchar(255) NOT NULL,
  `auth_token_id` varchar(255) DEFAULT NULL,
  `window_start` timestamp NOT NULL,
  `window_type` enum('hour','day','burst') NOT NULL,
  `request_count` int NOT NULL DEFAULT '0',
  `last_request_at` timestamp NULL DEFAULT NULL,
  `platform_limit_hit` tinyint(1) DEFAULT '0',
  `platform_limit_reset_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_rate_limit_window` (`template_id`,`auth_token_id`,`window_start`,`window_type`),
  KEY `idx_execution_template_rate_limits_template_id` (`template_id`),
  KEY `idx_execution_template_rate_limits_auth_token_id` (`auth_token_id`),
  KEY `idx_execution_template_rate_limits_window_start` (`window_start`),
  KEY `idx_execution_template_rate_limits_window_type` (`window_type`),
  CONSTRAINT `execution_template_rate_limits_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `execution_templates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_template_rate_limits_ibfk_2` FOREIGN KEY (`auth_token_id`) REFERENCES `execution_template_auth_tokens` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_template_version_functions` (
  `id` varchar(255) NOT NULL,
  `template_version_id` varchar(255) NOT NULL,
  `function_id` varchar(255) NOT NULL,
  `is_required` tinyint(1) NOT NULL DEFAULT '0',
  `execution_order` int DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_template_version_function` (`template_version_id`,`function_id`),
  KEY `idx_execution_template_version_functions_template_version_id` (`template_version_id`),
  KEY `idx_execution_template_version_functions_function_id` (`function_id`),
  CONSTRAINT `execution_template_version_functions_ibfk_1` FOREIGN KEY (`template_version_id`) REFERENCES `execution_template_versions` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_template_version_functions_ibfk_2` FOREIGN KEY (`function_id`) REFERENCES `function_definitions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_template_versions` (
  `id` varchar(255) NOT NULL,
  `template_id` varchar(255) NOT NULL,
  `version_number` int NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `template_prompt` text NOT NULL,
  `context_template` text,
  `enable_function_calling` tinyint(1) NOT NULL,
  `category` varchar(100) DEFAULT NULL,
  `tags` json,
  `rate_limit_per_hour` int DEFAULT NULL,
  `rate_limit_per_day` int DEFAULT NULL,
  `rate_limit_burst` int DEFAULT NULL,
  `change_summary` varchar(500) DEFAULT NULL,
  `change_type` enum('create','update','restore') NOT NULL DEFAULT 'update',
  `is_current_version` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_template_version` (`template_id`,`version_number`),
  KEY `user_id` (`user_id`),
  KEY `idx_execution_template_versions_template_id` (`template_id`),
  KEY `idx_execution_template_versions_version_number` (`template_id`,`version_number` DESC),
  KEY `idx_execution_template_versions_is_current` (`template_id`,`is_current_version`),
  KEY `idx_execution_template_versions_created_at` (`created_at`),
  CONSTRAINT `execution_template_versions_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `execution_templates` (`id`) ON DELETE CASCADE,
  CONSTRAINT `execution_template_versions_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `execution_templates` (
  `id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `template_prompt` text NOT NULL,
  `context_template` text,
  `enable_function_calling` tinyint(1) NOT NULL DEFAULT '0',
  `is_active` tinyint(1) NOT NULL DEFAULT '1',
  `is_public` tinyint(1) NOT NULL DEFAULT '0',
  `category` varchar(100) DEFAULT 'general',
  `tags` json,
  `execution_timeout_seconds` int DEFAULT '300',
  `rate_limit_per_hour` int DEFAULT '100',
  `rate_limit_per_day` int DEFAULT '1000',
  `rate_limit_burst` int DEFAULT '10',
  `total_executions` int DEFAULT '0',
  `last_executed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_template_name` (`user_id`,`name`),
  KEY `idx_execution_templates_user_id` (`user_id`),
  KEY `idx_execution_templates_is_active` (`is_active`),
  KEY `idx_execution_templates_is_public` (`is_public`),
  KEY `idx_execution_templates_category` (`category`),
  KEY `idx_execution_templates_created_at` (`created_at`),
  KEY `idx_execution_templates_enable_function_calling` (`enable_function_calling`),
  CONSTRAINT `execution_templates_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `function_calls` (
  `id` varchar(255) NOT NULL,
  `request_id` varchar(255) NOT NULL,
  `function_name` varchar(100) NOT NULL,
  `function_arguments` json,
  `function_response` json,
  `execution_status` varchar(50) DEFAULT 'pending',
  `execution_time_ms` int DEFAULT NULL,
  `error_details` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `sequence_number` int NOT NULL DEFAULT '0',
  `parent_call_id` varchar(255) DEFAULT NULL,
  `execution_depth` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `idx_function_calls_request_id` (`request_id`),
  KEY `idx_function_calls_sequence` (`request_id`,`sequence_number`),
  KEY `idx_function_calls_parent` (`parent_call_id`),
  CONSTRAINT `fk_function_calls_parent` FOREIGN KEY (`parent_call_id`) REFERENCES `function_calls` (`id`) ON DELETE SET NULL,
  CONSTRAINT `function_calls_ibfk_1` FOREIGN KEY (`request_id`) REFERENCES `api_requests` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `function_definitions` (
  `id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `display_name` varchar(100) NOT NULL,
  `function_group` varchar(100) NOT NULL DEFAULT 'general',
  `function_type` varchar(20) NOT NULL DEFAULT 'api',
  `description` text,
  `parameters_schema` json,
  `mock_response` json,
  `endpoint_url` varchar(500) DEFAULT NULL,
  `http_method` varchar(10) DEFAULT 'POST',
  `headers` json,
  `auth_config` json,
  `is_active` tinyint(1) DEFAULT '1',
  `is_system_resource` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `required_api_keys` json NOT NULL DEFAULT (json_array()),
  `api_key_validation` json NOT NULL DEFAULT (json_object()),
  `query_template` text,
  `result_transformer` varchar(50) DEFAULT 'default',
  `fallback_data` json,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_user_function` (`user_id`,`name`),
  KEY `idx_function_definitions_user_id` (`user_id`),
  CONSTRAINT `function_definitions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user_sessions` (
  `id` varchar(255) NOT NULL,
  `user_id` varchar(255) NOT NULL,
  `token` varchar(500) NOT NULL,
  `expires_at` timestamp NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`),
  KEY `idx_user_sessions_user_id` (`user_id`),
  KEY `idx_user_sessions_token` (`token`),
  CONSTRAINT `user_sessions_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `users` (
  `id` varchar(255) NOT NULL,
  `username` varchar(100) NOT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password_hash` varchar(255) NOT NULL,
  `email_verified` tinyint(1) DEFAULT '0',
  `is_temporary` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_login_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Re-enable foreign key checks
SET FOREIGN_KEY_CHECKS = 1;
